/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#23055c",
        "primary-container": "#392271",
        "on-primary": "#ffffff",
        "on-primary-container": "#a48de2",
        "on-primary-fixed": "#22025a",
        "on-primary-fixed-variant": "#4e3887",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#cfbdff",
        "inverse-primary": "#cfbdff",
        secondary: "#65519f",
        "secondary-container": "#bfa9fe",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#4e3a86",
        "secondary-fixed": "#e8ddff",
        "secondary-fixed-dim": "#cebdff",
        "on-secondary-fixed": "#210558",
        "on-secondary-fixed-variant": "#4d3985",
        tertiary: "#301700",
        "tertiary-container": "#4e2900",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#c68f5c",
        "tertiary-fixed": "#ffdcc0",
        "tertiary-fixed-dim": "#f7ba84",
        "on-tertiary-fixed": "#2d1600",
        "on-tertiary-fixed-variant": "#673d12",
        background: "#f7f9ff",
        "on-background": "#181c20",
        surface: "#f7f9ff",
        "surface-bright": "#f7f9ff",
        "surface-dim": "#d7dadf",
        "on-surface": "#181c20",
        "on-surface-variant": "#494550",
        "surface-variant": "#e0e3e8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f9",
        "surface-container": "#ebeef3",
        "surface-container-high": "#e5e8ee",
        "surface-container-highest": "#e0e3e8",
        "workspace-surface": "#F8F9FA",
        "accent-soft": "#EBE7F5",
        outline: "#7a7581",
        "outline-variant": "#cac4d2",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-tint": "#6651a1",
        "inverse-surface": "#2d3135",
        "inverse-on-surface": "#eef1f6",
        "ink-dark": "#1A1D20",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1280px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        gutter: "24px",
        unit: "8px",
      },
      fontFamily: {
        sans: ["Work Sans", "Inter", "system-ui", "sans-serif"],
        "label-sm": ["Work Sans", "sans-serif"],
        "label-md": ["Work Sans", "sans-serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "display-lg": ["Work Sans", "sans-serif"],
        "headline-sm": ["Work Sans", "sans-serif"],
        "display-lg-mobile": ["Work Sans", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "headline-md": ["Work Sans", "sans-serif"],
      },
      fontSize: {
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg-mobile": [
          "36px",
          { lineHeight: "42px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
