-- AlterTable
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "isBirthdayBonusEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "birthdayBonusCoins" DECIMAL(12,2) NOT NULL DEFAULT 500.00;
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "isStreakBonusEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "streakBonusCoins" DECIMAL(12,2) NOT NULL DEFAULT 200.00;
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "streakThresholdCount" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "streakWindowDays" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "isSignupBonusEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "signupBonusCoins" DECIMAL(12,2) NOT NULL DEFAULT 500.00;
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "isExpiryEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "expiryMonths" INTEGER NOT NULL DEFAULT 12;
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "referralRewardPercent" DECIMAL(5,2) NOT NULL DEFAULT 5.00;
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "referralFloorCoins" DECIMAL(12,2) NOT NULL DEFAULT 50.00;
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "referralCapCoins" DECIMAL(12,2) NOT NULL DEFAULT 1000.00;
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "referralWindowDays" INTEGER NOT NULL DEFAULT 90;
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "dailyAdjustmentLimitCoins" DECIMAL(12,2) NOT NULL DEFAULT 20000.00;
ALTER TABLE "loyalty_settings" ADD COLUMN IF NOT EXISTS "holdExpiryMinutes" INTEGER NOT NULL DEFAULT 15;
