/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#23055c",
        "primary-container": "#392271",
        "on-primary": "#ffffff",
        "on-primary-container": "#a48de2",
        "on-primary-fixed": "#22025a",
        "on-primary-fixed-variant": "#4e3887",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#cfbdff",
        "inverse-primary": "#cfbdff",
        secondary: "#65519f",
        "secondary-container": "#bfa9fe",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#4e3a86",
        "secondary-fixed": "#e8ddff",
        "secondary-fixed-dim": "#cebdff",
        "on-secondary-fixed": "#210558",
        "on-secondary-fixed-variant": "#4d3985",
        tertiary: "#301700",
        "tertiary-container": "#4e2900",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#c68f5c",
        "tertiary-fixed": "#ffdcc0",
        "tertiary-fixed-dim": "#f7ba84",
        "on-tertiary-fixed": "#2d1600",
        "on-tertiary-fixed-variant": "#673d12",
        background: "#f7f9ff",
        "on-background": "#181c20",
        surface: "#f7f9ff",
        "surface-bright": "#f7f9ff",
        "surface-dim": "#d7dadf",
        "on-surface": "#181c20",
        "on-surface-variant": "#494550",
        "surface-variant": "#e0e3e8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f9",
        "surface-container": "#ebeef3",
        "surface-container-high": "#e5e8ee",
        "surface-container-highest": "#e0e3e8",
        "workspace-surface": "#F8F9FA",
        "accent-soft": "#EBE7F5",
        outline: "#7a7581",
        "outline-variant": "#cac4d2",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-tint": "#6651a1",
        "inverse-surface": "#2d3135",
        "inverse-on-surface": "#eef1f6",
        "ink-dark": "#1A1D20",
        brand: {
          50: "#f4f7fa",
          100: "#e5ecf3",
          200: "#cedde9",
          300: "#a6c3da",
          400: "#77a2c6",
          500: "#5485b0",
          600: "#3f6b94",
          700: "#335677",
          800: "#1f3a68",
          900: "#182e52",
          950: "#0f1d35",
        },
        accent: {
          50: "#fff9eb",
          100: "#feeec7",
          200: "#fddc8a",
          300: "#fbc54d",
          400: "#f9ac1f",
          500: "#f08d08",
          600: "#d56c04",
          700: "#ab4a07",
          800: "#8c3a0d",
          900: "#74310e",
        },
      },
      fontFamily: {
        sans: ["Work Sans", "Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
